apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goapp-github
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/goapp-github/overlays/development
    repoURL: https://github.com/stephanie-cy/goapp-github-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
