apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: goapp-github
  janus-idp.io/tekton: goapp-github
  backstage.io/kubernetes-id: goapp-github
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp-github
resources: 
- deployment.yaml
- route.yaml
- service.yaml
